### ISSUE TITLE
If no english in project, do not show project on home page.

### ISSUE THREAD

**Issue by richardolsson** [zetkin/translators-interface#14]
To be discussed on Monday.

```
frontend_1  | TypeError: Cannot read property 'id' of undefined
frontend_1  |     at getServerSideProps (/var/app/.next/server/pages/projects/[id]/[language_code].js:242:82)
frontend_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
frontend_1  |     at async renderToHTML (/var/app/node_modules/next/dist/next-server/server/render.js:40:215)
frontend_1  |     at async /var/app/node_modules/next/dist/next-server/server/next-server.js:111:97
frontend_1  |     at async /var/app/node_modules/next/dist/next-server/server/next-server.js:104:142
frontend_1  |     at async Server.renderToHTMLWithComponents (/var/app/node_modules/next/dist/next-server/server/next-server.js:136:387)
frontend_1  |     at async Server.renderToHTML (/var/app/node_modules/next/dist/next-server/server/next-server.js:137:1088)
frontend_1  |     at async Server.render (/var/app/node_modules/next/dist/next-server/server/next-server.js:74:255)
frontend_1  |     at async Object.fn (/var/app/node_modules/next/dist/next-server/server/next-server.js:58:672)
frontend_1  |     at async Router.execute (/var/app/node_modules/next/dist/next-server/server/router.js:25:67)
```

**Comment by djbusstop** [comment]
If no english on the project, don't show it on the homepage.
